services:
  mongodb:
    image: mongo:7
    container_name: demart-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: demart-backend
    ports:
      - "8002:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=quotation_db
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: demart-frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8002
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true

volumes:
  mongo_data:
